server:
  port: 8081

spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

#    properties:
#      hibernate:
#        format_sql: true

    defer-datasource-initialization: true

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa # HS256 알고리즘을 사용하기 위해, 256비트보다 커야함
# access-token-validity-in-seconds: 600 # 10 min
